services:
  test:
    image: custom-luceneutil
    build:
      context: test-image
      dockerfile: Dockerfile.testbuild
      args:
        TEST_REPO: ${TEST_REPO}
        TEST_BRANCH: ${TEST_BRANCH}
        OPENSEARCH_VERSION: ${LUCENE_VERSION}
    container_name: test
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms${TEST_JVM} -Xmx${TEST_JVM} -XX:StartFlightRecording=delay=5s,dumponexit=true,filename=/share-data/profiles/${RUN_ID}.jfr"
      - "RUN_ID=${RUN_ID}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - test:/usr/share/lucene/data
      - share-data:/share-data
    deploy:
      resources:
        limits:
          cpus: ${TEST_CPU_COUNT}
          memory: ${TEST_MEM_SIZE}
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
volumes:
  test:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SHARE_DATA_PATH}/lucene-data
  metrics:
  share-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SHARE_DATA_PATH}
