# Build the plugin
ARG LUCENE_VERSION
FROM eclipse-temurin:23 as build
COPY ./build-lucene.sh /

ARG LUCENE_VERSION
ARG TEST_REPO
ARG TEST_BRANCH
RUN echo ${LUCENE_VERSION}
RUN bash /build-luceneutil.sh ${TEST_REPO} ${TEST_BRANCH} ${LUCENE_VERSION}

# Build the actual image
FROM eclipse-temurin:23
ARG LUCENE_VERSION
USER root
RUN yum install unzip procps -y
USER luceneutil
COPY custom-entrypoint.sh /custom-entrypoint.sh
COPY utils/process-stats-collector.sh /process-stats-collector.sh

ENTRYPOINT ["/bin/bash", "/custom-entrypoint.sh"]
