FROM opensearchproject/opensearch-benchmark:latest

USER 0
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "jq", "curl", "--assume-yes"]
USER 1000
COPY osb-entry-point.sh /
COPY benchmark.ini.patch /

ENTRYPOINT ["bash", "/osb-entry-point.sh"]
